name: Flutter Workflow

on: workflow_dispatch
defaults:
  run:
    working-directory: ./fluttertest/testapp

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.9"
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # - name: Setup Java to compile Android project
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: "temurin"
      #     java-version: "11.x"
      #     cache: "gradle"

      # - name: Download Android keystore
      #   id: android_keystore
      #   uses: timheuer/base64-to-file@v1.2
      #   with:
      #     fileName: upload-keystore.jks
      #     encodedString: ${{ secrets.KEY_STORE_2 }}

      # - name: Create key.properties
      #   run: |
      #     echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
      #     echo "storePassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
      #     echo "keyPassword=${{ secrets.KEY_STORE }}" >> android/key.properties
      #     echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      # - name: Start Android Release Build
      #   run: flutter build appbundle

      # - name: Install Apple Certificate
      #   uses: apple-actions/import-codesign-certs@v1
      #   with:
      #     p12-file-base64: ${{ secrets.P12_BASE64 }}
      #     p12-password: ${{ secrets.P12_PASSWORD }}

      # - name: Install the provisioning profile
      #   env:
      #     PROVISIONING_CERTIFICATE_BASE64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
      #   run: |
      #     PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision

      #     echo -n "$PROVISIONING_CERTIFICATE_BASE64" | base64 --decode --output $PP_PATH

      #     mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
      #     cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      # - name: Building IPA
      #   run: flutter build ipa --export-options-plist=ios/Runner/ExportOptions.plist

      - name: collect ipa artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-ipa
          # Path to the release files
          path: ./fluttertest/testapp/files/instrideipa/*.ipa
